name: Deploy project

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Install dependencies
        run: yarn install
      - run: yarn build
      - run: yarn test:unit
        env:
            COMMIT_EMAIL: ${{ secrets.DEPLOY_MAIL }}
            COMMIT_NAME: jhon
            ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
            BASE_BRANCH: main
            DEPLOY_BRANCH: gh-pages
            BUILD_SCRIPT: yarn && yarn build
            FOLDER: ${{ secrets.DEPLOY_DIR }}
