name: Deploy project

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Install dependencies
        run: yarn install

      - name: Config artifact
        uses: actions/upload-artifact@v2
        with:
          name: deploy
          path: |
            doc
            !doc/**/*.md
            !doc/**/*.map
            !doc/favicon.ico

      - name: Build project 
        run: yarn build

      - name: Run unitary test
        run: yarn test:unit

      - name: Config test 
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: |
            cypress/videos
            cypress/screenshots
          retention-days: 3

      - name: Run unitary e2e test 
        run: |
          yarn test:unit
          yarn serve &
          yarn test
